// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/ff_annotation_route
// **************************************************************************
// fast mode: true
// **************************************************************************
// ignore_for_file: prefer_const_literals_to_create_immutables,unused_local_variable,unused_import,unnecessary_import,unused_shown_name,implementation_imports,duplicate_import
/// The routeNames auto generated by https://github.com/fluttercandies/ff_annotation_route
const List<String> routeNames = <String>[
  '/addConversation',
  '/app',
  '/completeProfile',
  '/conversation',
  '/login',
  '/profile',
  '/signup',
  '/splash',
];

/// The routes auto generated by https://github.com/fluttercandies/ff_annotation_route
class RouteName {
  const RouteName._();

  /// '/addConversation'
  ///
  /// [name] : '/addConversation'
  static const String addConversation = '/addConversation';

  /// '/app'
  ///
  /// [name] : '/app'
  ///
  /// [routeName] : '/app'
  static const String app = '/app';

  /// '/completeProfile'
  ///
  /// [name] : '/completeProfile'
  static const String completeProfile = '/completeProfile';

  /// '/conversation'
  ///
  /// [name] : '/conversation'
  static const String conversation = '/conversation';

  /// '/login'
  ///
  /// [name] : '/login'
  static const String login = '/login';

  /// '/profile'
  ///
  /// [name] : '/profile'
  static const String profile = '/profile';

  /// '/signup'
  ///
  /// [name] : '/signup'
  static const String signup = '/signup';

  /// '/splash'
  ///
  /// [name] : '/splash'
  static const String splash = '/splash';
}
